version: '3'
services:
  web:
    image: harin1212/real-estate-backend:latest
    container_name: real-estate-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - kafka
    env_file: .env
    networks:
      - real-estate-network

  redis:
    image: redis:alpine
    container_name: real-estate-redis
    command: redis-server --port 6379
    hostname: real-estate-redis
    ports:
      - "6379:6379"
    networks:
      - real-estate-network

  zookeeper:
    image: harin1212/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - real-estate-network

  kafka:
    image: harin1212/kafka
    container_name: localhost
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "realestate:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - real-estate-network

networks:
  real-estate-network:
    driver: bridge
