version: '3'
services:
  web:
    image: harin1212/real-estate-backend:latest
    container_name: real-estate-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - kafka
      - mongo
    env_file: .env

  redis:
    image: redis:alpine
    container_name: real-estate-redis
    command: redis-server --port 6379
    hostname: real-estate-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "realestate:1:1"
    depends_on:
      - zookeeper

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
