spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/realEstate'
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 547494986205-pa6qvr12mft6i5sfvfsn1ljsnls33261.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            client-id: 134db93222a78ea32ff2c372e3314341
            client-secret: resJlMJtEadZvCqP7R7OMz4VqGVSMcSI
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
          naver:
            client-id: lfuNtUkE6WmI1ws45Ocn
            client-secret: t2tlqMACis
            client-name: Naver
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
jwt:
  secret-key: fast-campus.simple_sns_2022_secret_key
  # 30 days
  token.expired-time-ms: 2592000000
  secretKey: fast-campus.simple_sns_2022_secret_key
  refresh:
    expiration: 604800000
    header: Refresh-Token
  access:
    header: Authorization
    expiration: 604800000


image:
  save_path : ./images